export const FETCHING_RACE_LIST = "FETCHING_RACE_LIST";
export const FETCHING_RACES_LIST_SUCCESS = "FETCHING_RACES_LIST_SUCCESS";
export const FETCHING_RACE_LIST_ERROR = "FETCHING_RACE_LIST_ERROR";
export const SET_RACE_LIST = "SET_RACE_LIST";
export const SET_DISPLAYING_RACE_LIST = "SET_DISPLAYING_RACE_LIST";
export const SET_DISPLAYING_RACE_LIST_START_INDEX =
  "SET_DISPLAYING_RACE_LIST_START_INDEX";
export const REMOVE_RACE = "REMOVE_RACE";
export const SET_DISPLAYING_RACE_LIST_FILTER =
  "SET_DISPLAYING_RACE_LIST_FILTER";
